"""assignment Update

Revision ID: 2b46e9f6c1c0
Revises: 36696b78c60d
Create Date: 2025-04-19 18:37:50.864844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b46e9f6c1c0'
down_revision: Union[str, None] = '36696b78c60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_assignment_history', 'assigned_to_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('application_assignment_history', 'assigned_to_vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_assignment_history', 'assigned_to_vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('application_assignment_history', 'assigned_to_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
