"""relationship fix

Revision ID: 36696b78c60d
Revises: 85e2c7ed9349
Create Date: 2025-04-08 03:30:51.025590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36696b78c60d'
down_revision: Union[str, None] = '85e2c7ed9349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_details', sa.Column('verified_by_name', sa.String(length=100), nullable=True))
    op.drop_column('application_details', 'veerified_by_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_details', sa.Column('veerified_by_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('application_details', 'verified_by_name')
    # ### end Alembic commands ###
