"""initial migration

Revision ID: 85e2c7ed9349
Revises: 
Create Date: 2025-04-08 03:08:17.002579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e2c7ed9349'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visa_request',
    sa.Column('visa_request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visa_request_code', sa.String(length=50), nullable=False),
    sa.Column('visa_process_id', sa.Integer(), nullable=False),
    sa.Column('visa_type', sa.String(length=50), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('initiator_name', sa.String(length=100), nullable=False),
    sa.Column('initiator_email', sa.String(length=100), nullable=False),
    sa.Column('initiator_phone', sa.String(length=20), nullable=False),
    sa.Column('initiator_address', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('total_applicants', sa.Integer(), nullable=False),
    sa.Column('application_fee', sa.Integer(), nullable=False),
    sa.Column('visa_fee', sa.Integer(), nullable=False),
    sa.Column('service_fee', sa.Integer(), nullable=False),
    sa.Column('total_fee', sa.Integer(), nullable=False),
    sa.Column('total_fee_currency', sa.String(length=10), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'REFUNDED', name='payment_status_enum'), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('coupon_discount', sa.Integer(), nullable=True),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('coupon_type', sa.Enum('FLAT', 'PERCENTAGE', name='coupon_type_enum'), nullable=True),
    sa.Column('visa_status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', name='visa_status_enum'), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.Column('visa_request_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('visa_request_id'),
    sa.UniqueConstraint('visa_request_code')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visa_request_id', sa.Integer(), nullable=False),
    sa.Column('application_code', sa.String(length=50), nullable=False),
    sa.Column('applicant_first_name', sa.String(length=100), nullable=False),
    sa.Column('applicant_middle_name', sa.String(length=100), nullable=True),
    sa.Column('applicant_last_name', sa.String(length=100), nullable=True),
    sa.Column('applicant_email', sa.String(length=100), nullable=False),
    sa.Column('applicant_phone', sa.String(length=20), nullable=False),
    sa.Column('applicant_passport_number', sa.String(length=50), nullable=False),
    sa.Column('applicant_dob', sa.DateTime(), nullable=False),
    sa.Column('applicant_gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_enum'), nullable=False),
    sa.Column('application_status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'PROCESSING', name='application_status_enum'), nullable=True),
    sa.Column('submission_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=100), nullable=True),
    sa.Column('expected_completion_date', sa.DateTime(), nullable=True),
    sa.Column('application_notes', sa.String(), nullable=True),
    sa.Column('is_priority', sa.Boolean(), nullable=True),
    sa.Column('is_escilated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['visa_request_id'], ['visa_request.visa_request_id'], ),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('application_code')
    )
    op.create_table('application_assignment_history',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_by_name', sa.String(length=100), nullable=False),
    sa.Column('assigned_to_name', sa.String(length=100), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_vendor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_employee_id', sa.Integer(), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('assignment_status', sa.Enum('ASSIGNED', 'REASSIGNED', 'UNASSIGNED', name='assignment_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('application_details',
    sa.Column('application_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_code', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.String(length=100), nullable=False),
    sa.Column('field_title', sa.String(length=100), nullable=False),
    sa.Column('field_description', sa.String(length=255), nullable=True),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'DOCUMENT', name='field_type_enum'), nullable=False),
    sa.Column('document_type', sa.Enum('PASSPORT', 'PHOTO', 'VISA_FORM', 'OTHER', name='document_type_enum'), nullable=False),
    sa.Column('uploaded_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verification_status_enum'), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('veerified_by_name', sa.String(length=100), nullable=True),
    sa.Column('verified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('application_detail_id'),
    sa.UniqueConstraint('document_code')
    )
    op.create_table('application_remarks',
    sa.Column('remark_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('remark_type', sa.Enum('GENERAL', 'VERIFICATION', 'ESCALATION', name='remark_type_enum'), nullable=False),
    sa.Column('remark_text', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_internal', sa.Enum('YES', 'NO', name='is_internal_enum'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('remark_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_remarks')
    op.drop_table('application_details')
    op.drop_table('application_assignment_history')
    op.drop_table('applications')
    op.drop_table('visa_request')
    # ### end Alembic commands ###
